#!/usr/bin/env python3

import signal
try:
	from emoji_keyboard import emoji_shared as shared
	from emoji_keyboard import emoji_lib as lib
	from emoji_keyboard import emoji_gtk as egtk
except ImportError:
	from lib import emoji_shared as shared
	from lib import emoji_lib as lib
	from lib import emoji_gtk as egtk

handled_signals = {signal.SIGHUP, signal.SIGQUIT, signal.SIGTERM}

shared.lock = lib.Lock()                # Initialize lock, checks if lockfile
										# exists
shared.connection = lib.Connection()    # Initialize connection for sending,
										# but don't start the thread yet
shared.command = lib.Command()          # Parse command line flags and decide
										# if continue
										# The rest only runs if continue
shared.lock.lock()                      # Create lockfile
shared.manager = lib.Manager()
shared.clipboard = lib.Clipboard()
shared.emoji = egtk.Emoji()
shared.keyboard = egtk.Keyboard()
shared.search = egtk.Search()
shared.prefs = egtk.Preferences()
shared.indicator = egtk.Indicator()     # Again, initialize and store in shared
										# namespace, but don't start the main loop

for SIG in handled_signals:
	signal.signal(SIG, shared.manager.exit)

shared.connection.start()               # Now we can start listener and main loop
shared.indicator.start()
